//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2012/11/7 17:21:29
namespace CalligraphyEditor.CalligraphyData
{
    
    /// <summary>
    /// There are no comments for CalligraphyEntities in the schema.
    /// </summary>
    public partial class CalligraphyEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CalligraphyEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CalligraphyEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("CalligraphyModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("CalligraphyEditor.CalligraphyData", typeName.Substring(16)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CalligraphyEditor.CalligraphyData", global::System.StringComparison.Ordinal))
            {
                return string.Concat("CalligraphyModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for T_Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<T_Author> T_Author
        {
            get
            {
                if ((this._T_Author == null))
                {
                    this._T_Author = base.CreateQuery<T_Author>("T_Author");
                }
                return this._T_Author;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<T_Author> _T_Author;
        /// <summary>
        /// There are no comments for T_Dynast in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<T_Dynast> T_Dynast
        {
            get
            {
                if ((this._T_Dynast == null))
                {
                    this._T_Dynast = base.CreateQuery<T_Dynast>("T_Dynast");
                }
                return this._T_Dynast;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<T_Dynast> _T_Dynast;
        /// <summary>
        /// There are no comments for T_Photo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<T_Photo> T_Photo
        {
            get
            {
                if ((this._T_Photo == null))
                {
                    this._T_Photo = base.CreateQuery<T_Photo>("T_Photo");
                }
                return this._T_Photo;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<T_Photo> _T_Photo;
        /// <summary>
        /// There are no comments for T_Rubbing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<T_Rubbing> T_Rubbing
        {
            get
            {
                if ((this._T_Rubbing == null))
                {
                    this._T_Rubbing = base.CreateQuery<T_Rubbing>("T_Rubbing");
                }
                return this._T_Rubbing;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<T_Rubbing> _T_Rubbing;
        /// <summary>
        /// There are no comments for T_RubbingPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<T_RubbingPhoto> T_RubbingPhoto
        {
            get
            {
                if ((this._T_RubbingPhoto == null))
                {
                    this._T_RubbingPhoto = base.CreateQuery<T_RubbingPhoto>("T_RubbingPhoto");
                }
                return this._T_RubbingPhoto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<T_RubbingPhoto> _T_RubbingPhoto;
        /// <summary>
        /// There are no comments for T_Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToT_Author(T_Author t_Author)
        {
            base.AddObject("T_Author", t_Author);
        }
        /// <summary>
        /// There are no comments for T_Dynast in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToT_Dynast(T_Dynast t_Dynast)
        {
            base.AddObject("T_Dynast", t_Dynast);
        }
        /// <summary>
        /// There are no comments for T_Photo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToT_Photo(T_Photo t_Photo)
        {
            base.AddObject("T_Photo", t_Photo);
        }
        /// <summary>
        /// There are no comments for T_Rubbing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToT_Rubbing(T_Rubbing t_Rubbing)
        {
            base.AddObject("T_Rubbing", t_Rubbing);
        }
        /// <summary>
        /// There are no comments for T_RubbingPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToT_RubbingPhoto(T_RubbingPhoto t_RubbingPhoto)
        {
            base.AddObject("T_RubbingPhoto", t_RubbingPhoto);
        }
    }
    /// <summary>
    /// There are no comments for CalligraphyModel.T_Author in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("T_Author")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class T_Author : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new T_Author object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static T_Author CreateT_Author(int ID, string name)
        {
            T_Author t_Author = new T_Author();
            t_Author.ID = ID;
            t_Author.Name = name;
            return t_Author;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Nullable<bool> value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for T_Rubbing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<T_Rubbing> T_Rubbing
        {
            get
            {
                return this._T_Rubbing;
            }
            set
            {
                this._T_Rubbing = value;
                this.OnPropertyChanged("T_Rubbing");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<T_Rubbing> _T_Rubbing = new global::System.Data.Services.Client.DataServiceCollection<T_Rubbing>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CalligraphyModel.T_Dynast in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("T_Dynast")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class T_Dynast : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new T_Dynast object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static T_Dynast CreateT_Dynast(string name, int ID)
        {
            T_Dynast t_Dynast = new T_Dynast();
            t_Dynast.Name = name;
            t_Dynast.ID = ID;
            return t_Dynast;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Nullable<bool> value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for T_Rubbing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<T_Rubbing> T_Rubbing
        {
            get
            {
                return this._T_Rubbing;
            }
            set
            {
                this._T_Rubbing = value;
                this.OnPropertyChanged("T_Rubbing");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<T_Rubbing> _T_Rubbing = new global::System.Data.Services.Client.DataServiceCollection<T_Rubbing>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CalligraphyModel.T_Photo in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("T_Photo")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class T_Photo : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new T_Photo object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static T_Photo CreateT_Photo(int ID)
        {
            T_Photo t_Photo = new T_Photo();
            t_Photo.ID = ID;
            return t_Photo;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ContentType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this._ContentType = value;
                this.OnContentTypeChanged();
                this.OnPropertyChanged("ContentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentType;
        partial void OnContentTypeChanging(string value);
        partial void OnContentTypeChanged();
        /// <summary>
        /// There are no comments for Property FileSize in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> FileSize
        {
            get
            {
                return this._FileSize;
            }
            set
            {
                this.OnFileSizeChanging(value);
                this._FileSize = value;
                this.OnFileSizeChanged();
                this.OnPropertyChanged("FileSize");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _FileSize;
        partial void OnFileSizeChanging(global::System.Nullable<long> value);
        partial void OnFileSizeChanged();
        /// <summary>
        /// There are no comments for Property DateTimeAdded in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DateTimeAdded
        {
            get
            {
                return this._DateTimeAdded;
            }
            set
            {
                this.OnDateTimeAddedChanging(value);
                this._DateTimeAdded = value;
                this.OnDateTimeAddedChanged();
                this.OnPropertyChanged("DateTimeAdded");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DateTimeAdded;
        partial void OnDateTimeAddedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDateTimeAddedChanged();
        /// <summary>
        /// There are no comments for Property Width in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Width
        {
            get
            {
                return this._Width;
            }
            set
            {
                this.OnWidthChanging(value);
                this._Width = value;
                this.OnWidthChanged();
                this.OnPropertyChanged("Width");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Width;
        partial void OnWidthChanging(global::System.Nullable<double> value);
        partial void OnWidthChanged();
        /// <summary>
        /// There are no comments for Property Height in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<double> Height
        {
            get
            {
                return this._Height;
            }
            set
            {
                this.OnHeightChanging(value);
                this._Height = value;
                this.OnHeightChanged();
                this.OnPropertyChanged("Height");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<double> _Height;
        partial void OnHeightChanging(global::System.Nullable<double> value);
        partial void OnHeightChanged();
        /// <summary>
        /// There are no comments for T_RubbingPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto> T_RubbingPhoto
        {
            get
            {
                return this._T_RubbingPhoto;
            }
            set
            {
                this._T_RubbingPhoto = value;
                this.OnPropertyChanged("T_RubbingPhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto> _T_RubbingPhoto = new global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CalligraphyModel.T_Rubbing in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("T_Rubbing")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class T_Rubbing : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new T_Rubbing object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="authorID">Initial value of AuthorID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static T_Rubbing CreateT_Rubbing(int ID, string name, int authorID)
        {
            T_Rubbing t_Rubbing = new T_Rubbing();
            t_Rubbing.ID = ID;
            t_Rubbing.Name = name;
            t_Rubbing.AuthorID = authorID;
            return t_Rubbing;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property DynastID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DynastID
        {
            get
            {
                return this._DynastID;
            }
            set
            {
                this.OnDynastIDChanging(value);
                this._DynastID = value;
                this.OnDynastIDChanged();
                this.OnPropertyChanged("DynastID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DynastID;
        partial void OnDynastIDChanging(global::System.Nullable<int> value);
        partial void OnDynastIDChanged();
        /// <summary>
        /// There are no comments for Property AuthorID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int AuthorID
        {
            get
            {
                return this._AuthorID;
            }
            set
            {
                this.OnAuthorIDChanging(value);
                this._AuthorID = value;
                this.OnAuthorIDChanged();
                this.OnPropertyChanged("AuthorID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _AuthorID;
        partial void OnAuthorIDChanging(int value);
        partial void OnAuthorIDChanged();
        /// <summary>
        /// There are no comments for Property Collector in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Collector
        {
            get
            {
                return this._Collector;
            }
            set
            {
                this.OnCollectorChanging(value);
                this._Collector = value;
                this.OnCollectorChanged();
                this.OnPropertyChanged("Collector");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Collector;
        partial void OnCollectorChanging(string value);
        partial void OnCollectorChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Nullable<bool> value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for T_Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public T_Author T_Author
        {
            get
            {
                return this._T_Author;
            }
            set
            {
                this._T_Author = value;
                this.OnPropertyChanged("T_Author");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private T_Author _T_Author;
        /// <summary>
        /// There are no comments for T_Dynast in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public T_Dynast T_Dynast
        {
            get
            {
                return this._T_Dynast;
            }
            set
            {
                this._T_Dynast = value;
                this.OnPropertyChanged("T_Dynast");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private T_Dynast _T_Dynast;
        /// <summary>
        /// There are no comments for T_RubbingPhoto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto> T_RubbingPhoto
        {
            get
            {
                return this._T_RubbingPhoto;
            }
            set
            {
                this._T_RubbingPhoto = value;
                this.OnPropertyChanged("T_RubbingPhoto");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto> _T_RubbingPhoto = new global::System.Data.Services.Client.DataServiceCollection<T_RubbingPhoto>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for CalligraphyModel.T_RubbingPhoto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("T_RubbingPhoto")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class T_RubbingPhoto : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new T_RubbingPhoto object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static T_RubbingPhoto CreateT_RubbingPhoto(int ID)
        {
            T_RubbingPhoto t_RubbingPhoto = new T_RubbingPhoto();
            t_RubbingPhoto.ID = ID;
            return t_RubbingPhoto;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PageNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> PageNumber
        {
            get
            {
                return this._PageNumber;
            }
            set
            {
                this.OnPageNumberChanging(value);
                this._PageNumber = value;
                this.OnPageNumberChanged();
                this.OnPropertyChanged("PageNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _PageNumber;
        partial void OnPageNumberChanging(global::System.Nullable<int> value);
        partial void OnPageNumberChanged();
        /// <summary>
        /// There are no comments for Property RubbingID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> RubbingID
        {
            get
            {
                return this._RubbingID;
            }
            set
            {
                this.OnRubbingIDChanging(value);
                this._RubbingID = value;
                this.OnRubbingIDChanged();
                this.OnPropertyChanged("RubbingID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _RubbingID;
        partial void OnRubbingIDChanging(global::System.Nullable<int> value);
        partial void OnRubbingIDChanged();
        /// <summary>
        /// There are no comments for Property PhotoID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> PhotoID
        {
            get
            {
                return this._PhotoID;
            }
            set
            {
                this.OnPhotoIDChanging(value);
                this._PhotoID = value;
                this.OnPhotoIDChanged();
                this.OnPropertyChanged("PhotoID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _PhotoID;
        partial void OnPhotoIDChanging(global::System.Nullable<int> value);
        partial void OnPhotoIDChanged();
        /// <summary>
        /// There are no comments for Property IsDeleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsDeleted
        {
            get
            {
                return this._IsDeleted;
            }
            set
            {
                this.OnIsDeletedChanging(value);
                this._IsDeleted = value;
                this.OnIsDeletedChanged();
                this.OnPropertyChanged("IsDeleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsDeleted;
        partial void OnIsDeletedChanging(global::System.Nullable<bool> value);
        partial void OnIsDeletedChanged();
        /// <summary>
        /// There are no comments for T_Photo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public T_Photo T_Photo
        {
            get
            {
                return this._T_Photo;
            }
            set
            {
                this._T_Photo = value;
                this.OnPropertyChanged("T_Photo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private T_Photo _T_Photo;
        /// <summary>
        /// There are no comments for T_Rubbing in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public T_Rubbing T_Rubbing
        {
            get
            {
                return this._T_Rubbing;
            }
            set
            {
                this._T_Rubbing = value;
                this.OnPropertyChanged("T_Rubbing");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private T_Rubbing _T_Rubbing;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
